version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
      target: nginx
    ports:
      - "1234:80"

  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mongo


  mongo:
    build:
      context: ./db/monodrippy
      dockerfile: db.dockerfile
    ports:
      - "27017:27017"
    volumes:
      - ./db:/db