version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - "8080:8080"

  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mongo


  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./db/monodrippy/restore.sh:/docker-entrypoint-initdb.d/restore.sh
      - ./db:/db